project:
  type: default
  output-dir: _output

execute:
  freeze: auto
  echo: false
  warning: false

format:
  html:
    embed-resources: true
    self-contained: true
    theme: cosmo
    code-fold: true
    toc: true
    toc-depth: 3
    number-sections: true
    html-math-method:
      method: mathjax
  pdf:
    documentclass: article
    geometry:
      - margin=1in
    toc: true
    number-sections: true
    colorlinks: true
  typst:
    toc: true
    number-sections: true
    mainfont: "Libertinus Serif"
    papersize: us-letter
    keep-typ: true
    template-partials:
      - templates/typst-template.typ
      - templates/typst-show.typ

metadata-files:
  - _brand.yml
