#!/bin/bash
# Build and deploy FlexDamage documentation to GitHub Pages.
#
# Produces two views from the same source:
#   * docs/paper.html (single-page long-form, generated by Quarto)
#   * site/           (multi-page mkdocs site, includes paper.html as a static asset)
#
# Both are deployed to the gh-pages branch in one push:
#   * https://climateimpactlab.github.io/flex-damage/paper.html  (long-form)
#   * https://climateimpactlab.github.io/flex-damage/            (dev docs)
#
# Run from anywhere; the script cds to the repo root itself.

set -euo pipefail

# Quarto isn't on the default PATH on Midway; make sure it's discoverable
export PATH="$HOME/quarto-1.6.42/bin:$HOME/bin:$PATH"

cd "$(dirname "$0")/.."

echo "[1/2] Rendering long-form (docs/paper.html)..."
quarto render docs/paper.qmd --to html

echo "[2/2] Building mkdocs site and deploying to gh-pages..."
mkdocs gh-deploy --force

cat <<'EOF'

Deploy complete.
  Long-form:    https://climateimpactlab.github.io/flex-damage/paper.html
  Dev docs:     https://climateimpactlab.github.io/flex-damage/
EOF
